version: '3'
services:
  notebook:
    image: "graham/jupyter-notebook-jba:1.0"
    container_name: notebook
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan
  virtuoso-db:
    image: "tenforce/virtuoso"
    container_name: virtuoso-db
    ports:
      - "8890:8890"
    environment:
      - DBA_PASSWORD=dba
      - SPARQL_UPDATE=true
      - VIRT_SPARQL_ExternalQuerySource=true
    volumes:
      - ./data:/data
